auctions:
  - totalQuantity: 100
    firstParticipant:
      sum: 100
      strategy: SILLY
    secondParticipant:
      sum: 100
      strategy: COMPETE
  - totalQuantity: 100
    firstParticipant:
      sum: 100
      strategy: COMPETE
    secondParticipant:
      sum: 100
      strategy: COMPETE